version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8081:80
    volumes:
      - ./application:/var/www/html
      - ./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - mysql
    networks:
      - laravel

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./application:/var/www/html
    ports:
      - 9000:9000
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 33061:3306
    volumes:
      - ./environment/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: weather-db
      MYSQL_USER: weather-user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
